---
# Головной playbook для установки Kubernetes кластера
# Порядок выполнения:
# 1. bootstrap.yml - установка Python
# 2. master.yaml - установка Kubernetes на master
# 3. nat-gateway.yaml - настройка NAT (bastion) на master для доступа worker-нод в интернет
# 4. worker.yaml - установка Kubernetes на workers
# 5. kubeadm-init.yaml - инициализация кластера на master
# 6. kubeadm-join.yaml - присоединение workers к кластеру

- name: Bootstrap Python 3.9 on master node
  import_playbook: 01-bootstrap.yaml

- name: Install Kubernetes on master node
  import_playbook: 10-master.yaml

# - name: Configure NAT gateway on master node
#   import_playbook: 02-nat-gateway.yaml

- name: Install Kubernetes on worker nodes
  import_playbook: 11-worker.yaml

- name: Initialize Kubernetes cluster
  import_playbook: 20-kubeadm-init.yaml

- name: Join worker nodes to cluster
  import_playbook: 21-kubeadm-join.yaml
