[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../vault/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[master]
k8s-master ansible_host=89.169.156.149 private_ip=10.0.1.37

[workers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@89.169.156.149'

[workers] 
k8s-worker-01 ansible_host=10.0.1.23
k8s-worker-02 ansible_host=10.0.1.4
k8s-worker-03 ansible_host=10.0.1.22
k8s-worker-04 ansible_host=10.0.1.28
k8s-worker-05 ansible_host=10.0.1.11


[all:children]
master
workers